### ISSUE TITLE
Error 404: When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_...zip as ZipDeploy content

### ISSUE THREAD

**Issue by martin-greentrax** [Azure/functions-action#216]
These github workflows have worked 2 years for us to deploy various python functions hundreds of times to azure and now are suddenly no longer reliable:

```
      - name: Publish Azure Function
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
```
While debugging now we also tried v1.5.1, but no success with it either. Some more or less random restart/delete/disable may or may not help to resolve it (as described here https://github.com/microsoft/azure-pipelines-tasks/issues/18739#issuecomment-1905856749) but the issue comes back and then one can start the deployment over and over again and see the same error. 

Here is how the github job log starts with debug logging:

```
Current runner version: '2.311.0'
Operating System
Runner Image
  Image: ubuntu-22.04
  Version: 20240116.3.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
Runner Image Provisioner
  2.0.324.1
```

And this is how it fails:

```
##[debug]Deployment status: 0 'Building and Deploying '***-4e62-871a-d8bdc4ef87f0'.'. retry after 5 seconds
##[debug]setting affinity cookie ["ARRAffinity=****a443cf3f6c7c2e4daaee92c2062af1b69e3649bf26d43fe66fe700a7de;Path=/;HttpOnly;Secure;Domain=***.scm.azurewebsites.net","ARRAffinitySameSite=****443cf3f6c7c2e4daaee92c2062af1b69e3649bf26d43fe66fe700a7de;Path=/;HttpOnly;SameSite=None;Secure;Domain=***.scm.azurewebsites.net"]
##[debug][GET] [https://***.scm.azurewebsites.net:443/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY_FUNCTIONS_V1&time=2024-01-23_11-20-47Z](https://***.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY_FUNCTIONS_V1&time=2024-01-23_11-20-47Z)
##[debug]Could not parse response body.
##[debug]{}
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_8472975363497814.zip as ZipDeploy content
Error:     Failed to deploy web package to App Service.
Not Found (CODE: 404)
Error:       Error: Failed to deploy web package to App Service.
Not Found (CODE: 404)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:235:41)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Deployment Failed!
##[debug]Node Action run completed with exit code 1
```

It does seem to finish the publishing though (as our version tag shows the new version) but it does not start the remaining steps of the deployment as it considers this step as failed.

**Comment by martin-greentrax** [comment]
This issue keeps occurring randomly for our deployments. :(

**Comment by mboiman** [comment]
same here too. Microsoft fix this please!

**Comment by mboiman** [comment]
@patelchandni @Hazhzeng any ideas how to solve this problem?

**Comment by charlesgardyn** [comment]
Same here

**Comment by CaptainJojo** [comment]
Same here, I have error but it's deploy

**Comment by kuuselajuha** [comment]
Any solutions inbound? Having the same issue with v1.5.0 and 1.5.1

**Comment by niaher** [comment]
Same thing here - the builds suddenly started failing after 2 years. 

My workaround for now is use to https://github.com/Azure/webapps-deploy instead. Found the workaround in another related issue: https://github.com/Azure/functions-action/issues/213.

```
  - name: Deploy
    uses: azure/webapps-deploy@v2
    id: fa
    with:
      app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/build'
      publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
```

**Comment by skvark** [comment]
Same issue here as well...

**Comment by amorimcode** [comment]
same issue here

**Comment by kokatic** [comment]
same issue here!

**Comment by hynrbf** [comment]
Same issue here!

**Comment by kokatic** [comment]
Any alternative solutions to propose ?

**Comment by viachmev** [comment]
+1

**Comment by kokatic** [comment]
Hello Allo, 
I fixed the issue by resetting my 

- Redeploy my Azure Function
- Generate the Github Action Worflow file from the portal 

Hope this can help you !

**Comment by SjoerdTimovanVliet** [comment]
+1

**Comment by runeheidem** [comment]
+1

**Comment by ricardofalc** [comment]
Same issue here.

**Comment by MarcoP9** [comment]
Hey this issue is still existing for me. The re-deploy mentioned previously is not working, is there any attention on this?

**Comment by iMeany** [comment]
I got a similar error message in my workflow and have been trying to solve it for several days. I'm using RBAC instead of publish-profile, but maybe this still applies and helps someone:  

I disconnected the leftover configuration in the functions Deployment center (menu in Azure portal), even though I was NOT deploying through it, but through GitHub runner with RBAC credentials.  

No actual changes to the workflow itself or environment variables (I do have the `WEBSITE_RUN_FROM_PACKAGE=1` there since the beginning though.)

**Comment by Toanbego** [comment]
Hi.
I noticed, from the portal, that my function was not able to locate the workflow file in /.github/workflows/<name>.
The file was there, but had been converted to lower-case letters, and Azure expected some camel-case version of the filename. I changed the filename in the repository, and this solved the issue for me.

**Comment by jmicheldelibua** [comment]
Hi, 
I'm having the same issue. Sometimes works other not without make any changes.
Using version 1.5.2 and RBAC for auth.
Nothing yet?

**Comment by LukasSchauffele** [comment]
Any updates on this?

**Comment by patelchandni** [comment]
These are app specific issues, so please open a support ticket from Azure Portal if the issue still exists.

**Comment by chuanqisun** [comment]
😞 Still happening. I'm using RBAC. Tried disconnect and reconnect to GitHub repo without success. Any chance we can re-open the issue. I'm not sure I understand the maintainer's note:

> These are app specific issues, so please open a support ticket from Azure Portal if the issue still exists.

Based on the thread, the issue is not specific to an app. It is happening to quite a lot of people.

**Comment by jamesc601** [comment]
We are also suddenly experiencing this issue

**Comment by patelchandni** [comment]
ETA for release to complete across regions is 3 weeks from now i.e. July 15-18

**Comment by dubnemo** [comment]
So we are living with random publish issues until then?  Is there a publicly available roll out plan to view?  I feel like it is a complete waste of clock cycles in the meantime. 
And WHY is this issue "Closed" when it is clearly NOT.

**Comment by dubnemo** [comment]
If --output is going to be removed, then the documentation must be clear.  

This is NOT working:
```
        run: dotnet publish --property:PublishDir=${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
```
Whereas this is what works 20-30% of the time:
```
        run: dotnet publish --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
```
